# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ObjectiveCFirebaseProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ObjectiveCFirebaseProject
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
end
